name: MasterDeployCI
on:
#  on:
#    pull_request:
#      branches:
#        - master
#    push:
#      branches:
#        - master
  push:
    branches:
      - feature
      - master
env:
  DOCKER_CLI_EXPERIMENTAL: enabled
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v2
#    - name: Build the Docker image AND run tests
#      run: |
#        cd ./client
#        docker build -f Dockerfile.dev -t test_image .
#        docker run test_image npm test -- --coverage
      #-e CI=true
    - name: build images AND push to hub
#      if: github.ref == 'refs/heads/master'
      run: |
        echo ${DOCKER_PASSWORD} | docker login ${DOCKER_REGISTRY} -u ${DOCKER_USERNAME} --password-stdin

        echo "building '${CLIENT_IMAGE} image'"
        cd ./${CLIENT_IMAGE}
        docker build -f Dockerfile -t ${DOCKER_USERNAME}/${CLIENT_IMAGE}:${TAG} .
        docker push ${DOCKER_USERNAME}/${CLIENT_IMAGE}:${TAG}
        cd ..

        echo "building '${SERVER_IMAGE} image'"
        cd ./${SERVER_IMAGE}
        docker build -f Dockerfile -t ${DOCKER_USERNAME}/${SERVER_IMAGE}:${TAG} .
        docker push ${DOCKER_USERNAME}/${SERVER_IMAGE}:${TAG}
        cd ..

        echo "building '${NGINX_IMAGE} image'"
        cd ./${NGINX_IMAGE}
        docker build -f Dockerfile -t ${DOCKER_USERNAME}/${NGINX_IMAGE}:${TAG} .
        docker push ${DOCKER_USERNAME}/${NGINX_IMAGE}:${TAG}
        cd ..

        echo "building '${WORKER_IMAGE} image'"
        cd ./${WORKER_IMAGE}
        docker build -f Dockerfile -t ${DOCKER_USERNAME}/${WORKER_IMAGE}:${TAG} .
        docker push ${DOCKER_USERNAME}/${WORKER_IMAGE}:${TAG}
        cd ..
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_ID }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_AUTH }}
        DOCKER_REGISTRY: docker.io #registry.hub.docker.com
        TAG: latest
        CLIENT_IMAGE: client
        SERVER_IMAGE: server
        NGINX_IMAGE: nginx
        WORKER_IMAGE: worker
    - name: Check
      run: echo "Check health"
